### ISSUE TITLE
Update button overlaps buttons from BS+

### ISSUE THREAD

**Issue by AlexxSeven** [rithik-b/BeatSaverUpdater#1]
![image](https://user-images.githubusercontent.com/8524552/154787524-54ce3ca7-9b08-4972-889d-4f8dd714897a.png)
As described in the title. the button for updating the map overlaps the chat moderation button from bs+

**Comment by rithik-b** [comment]
As this button is more closely linked with the level and level metadata, I placed it here
There is no other place to place it, and this mod is compatible with all mods on beatmods/bsmg discord this way
Might be better to advice hardcpp to move the buttons instead, chat request can be placed in other places
