### ISSUE TITLE
Feature Request. Use the New Tags to Show a Map is Updatable

### ISSUE THREAD

**Issue by qe201020335** [rithik-b/BeatSaverUpdater#2]
The new 1.28.0 introduced these new level selector ui. I think maybe we can use this to indicate whether a map has an update or not.
![image](https://user-images.githubusercontent.com/31044781/222068421-f7e201ec-a03f-4a1a-9843-a5f4e6b8037b.png)
I'm pretty confident that these are just flags we can set to toggle the tags and the background because this is the 1.27.0 SongCore UI in 1.28.0 😄 
![_22DVZHN6I8G~HK)A8AU6EW](https://user-images.githubusercontent.com/31044781/222068699-e3f99542-c87b-40da-b34f-74c891a86562.png)

**Comment by qe201020335** [comment]
> I'm pretty confident that these are just flags we can set to toggle the tags

Yes it is
![image](https://user-images.githubusercontent.com/31044781/222082857-b37d2a9b-f1c3-44c6-87a7-97518bc1c96b.png)

**Comment by rithik-b** [comment]
Feel free to PR it if you like
I'm a little concerned about one thing: Could it be possible to throttle the requests to beatsaver to check for updates? Because here we would need to batch check a list of songs vs just one song at a time as a user requests it.

**Comment by qe201020335** [comment]
> Could it be possible to throttle the requests to beatsaver to check for updates?

I have an idea about this.
I got confirmation from Kinsi that SongDetailsCache only has the latest version of a map cached. This means we can safely exclude any maps whose hashes are in the SongDetailsCache's database (as long as the database is not outdated). 

What I think we can do is fetch all the hashes that are not found in SongDetailsCache after SongCore finishes loading. Beat saver's API allows up to 50 hashes in one request so we should be able to fetch all of them in just a couple of requests. 

I will try experimenting with this and hope it works out :)

**Comment by rithik-b** [comment]
Oh i didnt know about the 50 hashes thing
Please try it out and submit a PR, if youre stuck on something i can help out too

**Comment by qe201020335** [comment]
Sad that soon after I had this idea, the game UI changed so the badges are overlapping each other and it will not look good with SongRankedBadge
